language: nodejs

branches:
  only:
    - master

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm pack

before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "aajajim"
  - git config --local user.email "mohammed.aajaji.freelance@gmail.com"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "ardor-api-wrapper-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "mohammed.aajaji.freelance@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always