language: nodejs

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: 2389571803eaaccdafdae2f96d9a87f9d269d259
    on:
      tags: true
  - provider: releases
    api_key: 2389571803eaaccdafdae2f96d9a87f9d269d259
    file_glob: true
    file: "ardor-api-wrapper-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "mohammed.aajaji.freelance@gmail.com"
    api_key: 1bce3d9c-c32b-400b-89a4-4f5e998308f9
    on:
      tags: true